#cloud-config
package_update: true
package_upgrade: true

packages:
  - apache2
  - php
  - php-mysql
  - php-curl
  - php-gd
  - php-xml
  - php-mbstring
  - unzip
  - curl
  - cifs-utils
  - blobfuse2

runcmd:
  # 1. Postavi welcome/test HTML stranicu za provjeru
  - echo '<h1>Ovo je test stranica od studenta Pero</h1>' > /var/www/html/index.html
  - systemctl restart apache2

  # 2. MOUNT FILE SHARE (Azure File Share)
  - mkdir -p /mnt/share-wp
  - >
    mount -t cifs
    //${storageAccount}.file.core.windows.net/${fileShareName}
    /mnt/share-wp
    -o vers=3.0,username=${storageAccount},password=${storageKey},dir_mode=0777,file_mode=0777,serverino

  # 3. MOUNT BLOB STORAGE (blobfuse2)
  - mkdir -p /mnt/blob-wp
  - mkdir -p /etc/blobfuse2
  - |
    echo "
    {
      \"version\": 2,
      \"logging\": { \"type\": \"syslog\", \"level\": \"LOG_DEBUG\", \"file\": \"/dev/null\" },
      \"components\": [
        {
          \"lib\": \"azstorage_blobfuse2\",
          \"mount\": {
            \"accountName\": \"${storageAccount}\",
            \"accountKey\": \"${storageKey}\",
            \"containerName\": \"wpblob\"
          }
        }
      ]
    }
    " > /etc/blobfuse2/blobfuse2.json
  - blobfuse2 mount /mnt/blob-wp --config-file=/etc/blobfuse2/blobfuse2.json

  # 4. Daj svim korisnicima pristup montiranim direktorijima
  - chmod 777 /mnt/share-wp
  - chmod 777 /mnt/blob-wp

  # 5. DODATNO: Test fajlovi
  - echo "TEST BLOBFUSE2 MOUNT" > /mnt/blob-wp/proba.txt
  - echo "TEST FILESHARE MOUNT" > /mnt/share-wp/proba.txt

users:
  - name: ${adminUsername}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh-authorized-keys:
      - ${sshKey}      # obavezno!
      - ${sshKeyPero}  # dodatni za admin pristup
      - ${sshKeyMario} # dodatni za admin pristup

